### PR TITLE
Fix data persistence

### LINKED ISSUE #43: Playground data is not persisted
Reloading the extension, wipes all data.

How to reproduce:

1. Comment out [these lines](https://github.com/WordPress/try-wordpress/blob/trunk/src/ui/preview/Playground.tsx#L76-L78), so that we don't delete all posts. (This code will also need to be adapted because this currently deletes all posts, but this is not the cause of the issue).
2. `npm run start`
3. In the Admin tab, create a post
4. Navigate to the list of posts, in the Admin, and verify that the post is there
5. Reload the extension through the browser developer tools (Cmd+R when the developer tools window is in focus)
6. Navigate to the list of posts, in the Admin.
7. The post that was created in 3. is not listed in the list of posts

### PR DESCRIPTION
**Pull request by psrpinto**
Fixes #43 

WIP

### CODE REVIEW

**Comment by brandonpayton** [comment]
Hi @psrpinto, I pushed [a commit](https://github.com/WordPress/try-wordpress/pull/44/commits/125663c2cee45c68b0308c757cd0cc04f950e9ed) that updates this PR to use the updated `startPlaygroundWeb()` interface. I hope you don't mind. This is just an example, and the target directory name is arbitrary. (That said, maybe it would be good to place all try-wordpress sites in a parent OPFS folder like `/try-wordpress-sites` to avoid possible conflict with the playground.wordpress.net web app)

On first load it works and writes to OPFS, but on next load it breaks because it defaults to trying to install WordPress over top of existing files.

Screenshot 2024-09-30 at 8 35 19 PM

To fix this, you'll need to pass a `shouldInstallWordPress` flag to `startPlaygroundWeb()` after there is already a WordPress installation in the target OPFS directory. I _think_ you should have access to OPFS on playground.wordpress.net because you're in a content script.

You could use a heuristic when examining the target OPFS directory like:
https://github.com/WordPress/wordpress-playground/blob/8140715a273cefc503b87604e8ae397e112bfe92/packages/playground/website/src/lib/state/redux/boot-site-client.ts#L225

Actually... reading over boot-site-client.ts in general may be fairly informative. Does that help all?

**Comment by psrpinto** [comment]
Thanks for looking into this @brandonpayton! Mentioning @ashfame in case he hasn't seen your comment, as he's working on this issue.

**Comment by brandonpayton** [comment]
> To fix this, you'll need to pass a `shouldInstallWordPress` flag to `startPlaygroundWeb()` after there is already a WordPress installation in the target OPFS directory. I _think_ you should have access to OPFS on playground.wordpress.net because you're in a content script.

I was wrong about this because the content script in the imported website does not have the origin playground.wordpress.net.

We will need to either add Playground APIs for examining the FS on playground.wordpress.net, which is probably a bad idea from a security perspective**, or we can add a new param setting to `startPlaygroundWeb()` like `shouldInstallWordPress: auto` that asks Playground to judge for itself whether a WordPress install is needed.

** It might even be a bad idea to be trusting OPFS paths as we do.)

**Comment by brandonpayton** [comment]
> We will need to either add Playground APIs for examining the FS on playground.wordpress.net, which is probably a bad idea from a security perspective**, or we can add a new param setting to startPlaygroundWeb() like shouldInstallWordPress: auto that asks Playground to judge for itself whether a WordPress install is needed.

I'm hoping to create a Playground PR for this in the next day or so.

**Comment by psrpinto** [comment]
We found a temporary solution for now (see #71), so closing this one. Thanks for your help @brandonpayton!

**Pull request closed without merging**
