### PR TITLE
mu-plugin in playground to disable REST API auth

### PR DESCRIPTION
**Pull request by ashfame**
This PR effectively solves our "how to auth" with REST API problem since we do this in playground specific to our browser extension and not in general with the backend plugin.

I ended up trying this "disabling auth" approach because with using password approach, that works with application passwords and not just regular user's password. And even with application passwords, there wasn't an easy way to communicate that to frontend once we create and set that up. Options exist for development purposes but not so much for prod, when folks are using this extension out in the wild.

I think this playground specific effect is quite a good option. Thoughts?

### CODE REVIEW

**Comment by psrpinto** [comment]
This is a great solution! However, it doesn't seem to be working, I haven't looked into why that is.

I added a temporary button to create a post (we can delete it before merging this). After clicking the button,  in the extension console, you can see that the response is 401: `Sorry, you are not allowed to create posts as this user`.

**Comment by ashfame** [comment]
I haven't tested it in this repo (meaning from the frontend in this repo), but a simple curl command to the REST API and it worked. 401 without it, and successful post creation with it. I will do some digging.

**Comment by ashfame** [comment]
@psrpinto You can try now & once you remove the test button, mark this as approved, so that I can merge :)

don't mind the failing test, its from test code, which will be gone.

**Comment by psrpinto** [comment]
I removed the button and took the liberty of improving a couple of things.

**Review by psrpinto — APPROVED** [review]

**Comment by ashfame** [comment]
@psrpinto Excellent! I see `createPost()` is still there, intentional?

**Comment by ashfame** [comment]
@psrpinto confirmed its intentionally kept there for reference, so merging now.

**Pull request merged**
