### PR TITLE
Call schema validation from build process

### PR DESCRIPTION
**Pull request by psrpinto**
This PR merges the `schemas/` directory (#145) into `schema/` (from #146).

Additionally, it makes some extra changes:

- Because when we do schema validation we have to load all schemas into memory, I thought it would make sense that we also generate the final `schema.json` at that point. So here I changed `validate.mjs` into `build.mjs` which now does both validation and generation of the final `schema.json`.
- The final `schema.json` file is generated into the `schema/` directory itself, but hidden from git
- Then I changed webpack so that it just calls `build.mjs` and then reads the generated `schema.json`, instead of webpack itself having logic for generating the final `schema.json`.
- This makes it possible to centralize the logic of building the schema into one place (`schema/build.mjs`), which can also be ran from the CLI.
- I also moved the individual schemas into a `schema/subjects` directory, so that they are separate from all other files
- I also added a `build:schema` script to `package.json`

Screenshot 2024-12-10 at 17 21 27

### CODE REVIEW

**Comment by psrpinto** [comment]
There's currently an issue that causes the `npm run start:firefox` to go into an infinite loop. That issue is already present on trunk, so it's not introduced by this PR. I'm looking into it.

**Comment by ashfame** [comment]
Fixed in #150

**Comment by psrpinto** [comment]
Cool, thanks for fixing. Should we merge this one? Or you wanted to merge #150 into here?

**Comment by ashfame** [comment]
@psrpinto Will merge #150 in this one and then you can merge it to trunk, if that's alright?

**Comment by psrpinto** [comment]
Yep, that works 👍

**Review by ashfame — APPROVED** [review]
Nicely done!

**Review by ashfame — APPROVED** [review]
🚀

**Pull request merged**
